export enum HotelImagesActionTypes {
  FETCH_HOTEL_IMAGES_REQUEST = 'FETCH_HOTEL_IMAGES_REQUEST',
  FETCH_HOTEL_IMAGES_SUCCESS = 'FETCH_HOTEL_IMAGES_SUCCESS',
  FETCH_HOTEL_IMAGES_ERROR = 'FETCH_HOTEL_IMAGES_ERROR',
}
