export enum HotelCommentActionTypes {
  FETCH_HOTEL_COMMENTS_REQUEST = 'FETCH_HOTEL_COMMENTS_REQUEST',
  FETCH_HOTEL_COMMENTS_SUCCESS = 'FETCH_HOTEL_COMMENTS_SUCCESS',
  FETCH_HOTEL_COMMENTS_ERROR = 'FETCH_HOTEL_COMMENTS_ERROR',
  CREATE_COMMENT = 'CREATE_COMMENT',
}
